# Generated by Django 5.1.1 on 2024-09-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_auth_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
