# Generated by Django 5.1.1 on 2024-09-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0005_alter_profile_bio_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='default_pictures/default_profile_picture'),
        ),
    ]
