# Generated by Django 5.1.1 on 2024-09-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0006_alter_siteconfig_default_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='default_pictures/default_profile_picture.png'),
        ),
    ]
