# Generated by Django 5.1.1 on 2024-09-17 21:23

import userManage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0007_alter_siteconfig_default_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=userManage.models.get_default_profile_picture_path),
        ),
    ]
