# Generated by Django 3.2.25 on 2024-10-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0008_alter_siteconfig_default_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
