# Generated by Django 3.2.25 on 2024-10-18 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManage', '0009_profile_online_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('blockedUsers', models.ManyToManyField(blank=True, related_name='blockedUsers', to=settings.AUTH_USER_MODEL)),
                ('friendList', models.ManyToManyField(blank=True, related_name='friendList', to=settings.AUTH_USER_MODEL)),
                ('friendRequest', models.ManyToManyField(blank=True, related_name='friendRequest', to=settings.AUTH_USER_MODEL)),
                ('friendRequestSent', models.ManyToManyField(blank=True, related_name='friendRequestSent', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
